export const expertReviewManagerRestEndpoints = {
    health: '{0}/health',
    version: '{0}/version',
    reviews: '{0}/api/reviews/{1}',
    review: '{0}/api/reviews/{1}/applications/{2}',
    getSentReviews: '{0}/api/reviews/{1}/applications/{2}/sent-reviews',
    acceptTerms: '{0}/api/reviews/{1}/applications/{2}/accept-terms',
    sendReviewReadyEmail: '{0}/api/jobs/sendReviewReadyEmail/{1}',
    evaluateUsability: '{0}/api/reviews/review/{1}/evaluateUsability',
    sendReviews: '{0}/api/reviews/{1}/applications/{2}/sendReviews',
    getUsability: '{0}/api/reviews/review/{1}/usability',
    getApplicationsStatistics: '{0}/api/statistics/applications',
    createReviewer: '{0}/api/reviewers',
    getReviewers: '{0}/api/reviewers?applicationId={1}',
    getBlocklistedReviewers: '{0}/api/reviewers?applicationId={1}&shortListed=false',
    overruleConflictReport: '{0}/api/reviewers/jobs/overruleConflictReport',
    failReviewGroup: '{0}/api/review-group/applications/{1}/fail',
    getReviewGroupStatus: '{0}/api/review-group/applications/{1}/status',
    getReviewGroupStatuses: '{0}/api/review-group/applications/statuses',
};
