export const inviteServiceRestEndpoints = {
    health: '{0}/health',
    version: '{0}/version',
    getInvites: '{0}/api/invites/?resourceId={1}',
    getInvitePreview: '{0}/api/invites/{1}/preview',
    getCancelPreview: '{0}/api/invites/{1}/cancelPreview',
    createInvite: '{0}/api/invites/',
    sendInvite: '{0}/api/invites/jobs/sendInvite',
    cancelInvite: '{0}/api/invites/jobs/cancelInvite',
    getInvitesByResourceList: '{0}/api/invites/jobs/getInvitesByResourceIdList',
    getPureInvitesByContactId: '{0}/api/invites/pure?contactId={1}',
    getInviteCodeStatus: '{0}/api-anon/invite-code/{1}/status',
    acceptInvite: '{0}/api-anon/invite-code/{1}/accept',
    declineInvite: '{0}/api-anon/invite-code/{1}/decline',
    doesInviteeHaveAccount: '{0}/api-anon/invite-code/{1}/doesInviteeHaveAnAccount',
    getInvitee: '{0}/api/invite-code/{1}/invitee',
    getInviteCode: '{0}/api/invite-code?inviteId={1}',
    getInviteByInviteCode: '{0}/api/invite-code/{1}',
    createInviteLink: '{0}/api/invites/{1}/inviteLink',
    sendInviteReminders: '{0}/api/invites/jobs/sendInviteReminders',
    getInvitePreviewByPersonAndResourceId: '{0}/api/invites/preview?applicationId={1}&personId={2}',
    sendReviewerInvite: '{0}/api/invites/sendInvite',
};
