export const opportunityManagerRestEndpoints = {
    after_submission_what_happens_next_content: '{0}/api/application-workflow-components/{1}/post-submission-content',
    application_component_MAC: '{0}/api/opportunities/{1}/workflow-components/{2}/completion-status',
    close: '{0}/api/opportunities/job/close',
    costPolicy_and_categories: '{0}/api/opportunities/{1}/cost-policies',
    resources_and_costs: '{0}/api/opportunities/{1}/application-components/{2}/full-resources-and-costs',
    update_resources_and_costs: '{0}/api/opportunities/{1}/application-components/{2}/full-resources-and-costs/{3}',
    health: '{0}/health',
    open: '{0}/api/opportunities/job/open',
    opportunities: '{0}/api/opportunities?opportunityIds={1}&summary={2}',
    opportunity_application_component_resource_policy:
        '{0}/api/opportunities/{1}/application-components/{2}/resource-policy',
    opportunity: '{0}/api/opportunities/{1}',
    opportunityApplicationComponentPolicyRoles: '{0}/api/opportunities/{1}/application-components/{2}/roles',
    summary: '{0}/api/opportunities/{1}/summary',
    update_costPolicy_and_categories: '{0}/api/opportunities/{1}/cost-policies/{2}',
    update_application_component_section: '{0}/api/application-workflow-components/{1}/question-sets/{2}',
    workflow_component_list: '{0}/api/opportunities/{1}/workflow-components?includeApplicationMetadata={2}',
    workflow_component: '{0}/api/opportunities/{1}/workflow-components/{2}',
    delete_application_component_section: '{0}/api/opportunities/{1}/application-components/{2}/question-sets/{3}',
    delete_opportunity_component: '{0}/api/opportunities/{1}/workflow-components/{2}',
    policy_roles: '{0}/api/policy-roles',
    latest_policy_roles: '{0}/api/policy-roles/latest?awardType={1}',
    default_policy_role: '{0}/api/opportunities/{1}/default-role',
    project_partners: '{0}/api/opportunities/{1}/application-components/{2}/project-partners',
    project_partners_questionset: '{0}/api/opportunities/{1}/application-components/{2}/project-partners/{3}',
    handle_decision: '{0}/api/opportunities/{1}/decisions',
    update_opportunity: '{0}/api/opportunities/{1}',
};
